name: Create Plugin Zip

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Create zip file
      run: |
        zip -r remove-empty-shortcodes.zip . -x "*.git*" "*.github*" "*.gitignore" "CHANGELOG.md" "README.md"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: remove-empty-shortcodes
        path: remove-empty-shortcodes.zip

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: remove-empty-shortcodes.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}